server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:csafinal.jks
    key-store-password: csafinalproj
    key-store-type: PKCS12
    key-alias: my_ssl_key

spring:
  application:
    name: csa-final-project-backend
